import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import { getPortfolioSlugs, getPortfolioItem } from '../../lib/data'

export const getStaticPaths = async () => {
  const slugRes = await getPortfolioSlugs()
  const slugs = slugRes.portfolios

  console.log(slugs)

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  }
}

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug)

  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
    },
  }
}

export default function Home({ portfolioItem }) {
  console.log(portfolioItem)

  return (
    <div>
      <Head>
        <title>Sam&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{portfolioItem.title}</h1>
        <p>{portfolioItem.description}</p>
        <div>
          {portfolioItem.tags.map((tag) => (
            <span key={tag}>{tag}</span>
          ))}
          <Image
            src={portfolioItem.coverImage.url}
            width={portfolioItem.coverImage.width}
            height={portfolioItem.coverImage.height}
            alt=""
          />
        </div>
      </div>
    </div>
  )
}
