import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import he from 'he'
import { MDXRemote } from 'next-mdx-remote'
import { serialize } from 'next-mdx-remote/serialize'

import { getPortfolioSlugs, getPortfolioItem } from '../../lib/data'

export const getStaticPaths = async () => {
  const slugRes = await getPortfolioSlugs()
  const slugs = slugRes.portfolios

  console.log(slugs)

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  }
}

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug)

  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
      content: await serialize(he.decode(portfolioItem.portfolios[0].content)),
    },
  }
}

export default function Home({ portfolioItem, content }) {
  console.log(portfolioItem)

  return (
    <div>
      <Head>
        <title>Sam&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-0">
        <h1 className="text-6xl text-gray-900 font-bold">
          {portfolioItem.title}
        </h1>
        <div className="flex justify-between items-center">
          <p className="text-gray-700">
            {new Date(portfolioItem.date).toDateString()}
          </p>
          <div className="flex space-x-3 mt-2">
            {portfolioItem.tags.map((tag) => (
              <span
                className="text-white uppercase text-sm tracking-wide m-2 bg-gray-100 text-gray-900 px-2 py-1 rounded-lg"
                key={tag}>
                {tag}
              </span>
            ))}
          </div>
        </div>

        <p className="prose prose-xl py-4">{portfolioItem.description}</p>
        <Image
          src={portfolioItem.coverImage.url}
          width={portfolioItem.coverImage.width}
          height={portfolioItem.coverImage.height}
          alt={portfolioItem.title}
        />

        <div className="prose prose-xl max-w-none mt-4">
          {<MDXRemote {...content} />}
        </div>
      </div>
    </div>
  )
}
