import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import he from 'he'
import { MDXRemote } from 'next-mdx-remote'
import { serialize } from 'next-mdx-remote/serialize'

import { getPortfolioSlugs, getBlogSlugs, getPost } from '../../lib/data'

export const getStaticPaths = async () => {
  const slugRes = await getBlogSlugs()
  const slugs = slugRes.posts

  console.log(slugs)

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  }
}

export const getStaticProps = async ({ params }) => {
  const post = await getPost(params.slug)

  return {
    props: {
      post: post.posts[0],
      content: await serialize(he.decode(post.posts[0].content)),
    },
  }
}

export default function Home({ post, content }) {
  console.log(post)

  return (
    <div>
      <Head>
        <title>Sam&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-0">
        <h1 className="text-6xl text-gray-900 font-bold">{post.title}</h1>
        <div className="flex space-x-3 mt-2">
          {post.tags.map((tag) => (
            <span
              className="text-white uppercase text-sm tracking-wide m-2 bg-gray-100 text-gray-900 px-2 py-1 rounded-lg"
              key={tag}>
              {tag}
            </span>
          ))}
        </div>

        <div className="flex justify-between items-center">
          <p className="text-gray-700">{new Date(post.date).toDateString()}</p>

          <div className="flex items-center">
            <p className="mr-4 text-gray-800 tex-lg font-semibold">
              {post.author.name}
            </p>
            <Image
              className="rounded-full"
              src={post.author.image.url}
              width={75}
              height={75}
              objectFit="cover"
              alt={post.title}
            />
          </div>
        </div>

        <div className="prose prose-xl max-w-none">
          {<MDXRemote {...content} />}
        </div>
      </div>
    </div>
  )
}
