import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import he from 'he'
import { MDXRemote } from 'next-mdx-remote'
import { serialize } from 'next-mdx-remote/serialize'

import { getPortfolioSlugs, getBlogSlugs, getPost } from '../../lib/data'

export const getStaticPaths = async () => {
  const slugRes = await getBlogSlugs()
  const slugs = slugRes.posts

  console.log(slugs)

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  }
}

export const getStaticProps = async ({ params }) => {
  const post = await getPost(params.slug)

  return {
    props: {
      post: post.posts[0],
      content: await serialize(he.decode(post.posts[0].content)),
    },
  }
}

export default function Home({ post, content }) {
  console.log(post)

  return (
    <div>
      <Head>
        <title>Sam&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{post.title}</h1>
        <p>{new Date(post.date).toDateString()}</p>
        <p>{post.description}</p>
        <div>
          {post.author.name}
          <Image
            src={post.author.image.url}
            width={post.author.image.width / 4}
            height={post.author.image.height / 4}
            alt=""
          />
        </div>

        <div>
          {post.tags.map((tag) => (
            <span key={tag}>{tag}</span>
          ))}
        </div>
        <div>{<MDXRemote {...content} />}</div>
      </div>
    </div>
  )
}
