import { getPostsAndPortfolios } from '../lib/data'
import Head from 'next/head'
import Link from 'next/link'

export const getStaticProps = async () => {
  const data = await getPostsAndPortfolios()
  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Sam&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div>
        {data.portfolios?.map((item) => (
          <div key={item.slug}>
            <Link href={`/portfolio/${item.slug}`}>
              <a>{item.title}</a>
            </Link>
          </div>
        ))}
      </div>
      <div className="mt-10">
        {data.posts?.map((post) => (
          <div key={post.slug}>
            <Link href={`/blog/${post.slug}`}>{post.title}</Link>
          </div>
        ))}
      </div>
    </div>
  )
}
